language: php
sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  fast_finish: true
  include:
    - php: 7.0
    - php: 7.1

before_install:
  - composer self-update
  - curl -L https://github.com/FriendsOfPHP/PHP-CS-Fixer/releases/download/v2.1.0/php-cs-fixer.phar -o php-cs-fixer

install:
  - composer install

script:
  - ./vendor/bin/phpunit
  - ./php-cs-fixer fix --diff --dry-run -v
  - ./bin/console lint:yaml app/config
  - ./bin/console lint:twig app/Resources
  - ./bin/console security:check