<?php

namespace AppBundle\Repository;

/**
 * DesicionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DesicionRepository extends \Doctrine\ORM\EntityRepository
{
}
