<?php

namespace AppBundle\Repository;

/**
 * ReportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReportRepository extends \Doctrine\ORM\EntityRepository
{
    public function findOneByReference($reference)
    {
        return $this->createQueryBuilder('r')
            ->where('r.reference = :reference')->setParameter('reference', $reference)
            ->getQuery()
            ->getOneOrNullResult()
        ;
    }
}
