<?php

namespace AppBundle\Repository;

use AppBundle\Entity\User;

/**
 * ReportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReportRepository extends \Doctrine\ORM\EntityRepository
{
    public function findOneByReference($reference)
    {
        return $this->createQueryBuilder('r')
            ->where('r.reference = :reference')->setParameter('reference', $reference)
            ->getQuery()
            ->getOneOrNullResult()
        ;
    }

    public function getQueryForPagination(User $createdBy = null, $firstResult = 0, $maxResults = 10)
    {
        $qb = $this->createQueryBuilder('r')
            ->addSelect('uc')
            ->addSelect('ua')
            ->addSelect('d')
            ->leftJoin('r.createdBy', 'uc')
            ->leftJoin('r.addressedTo', 'ua')
            ->leftJoin('r.decisions', 'd')
            ->setFirstResult($firstResult)
            ->setMaxResults($maxResults)
        ;

        if ($createdBy) {
            $qb->where('r.createdBy = :createdBy')->setParameter('createdBy', $createdBy);
        }

        return $qb->getQuery();
    }

    public function count(User $createdBy = null)
    {
        $qb = $this->createQueryBuilder('r')->select('count(r.id)');

        if ($createdBy) {
            $qb->where('r.createdBy = :createdBy')->setParameter('createdBy', $createdBy);
        }

        return $qb->getQuery()->getSingleScalarResult();
    }
}
