<?php

namespace AppBundle\Repository;

/**
 * ReportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReportRepository extends \Doctrine\ORM\EntityRepository
{
    public function findOneByReference($reference)
    {
        return $this->createQueryBuilder('r')
            ->where('r.reference = :reference')->setParameter('reference', $reference)
            ->getQuery()
            ->getOneOrNullResult()
        ;
    }

    public function getQueryForPagination($firstResult = 0, $maxResults = 10)
    {
        return $this->createQueryBuilder('r')
            ->addSelect('uc')
            ->addSelect('ua')
            ->addSelect('d')
            ->join('r.createdBy', 'uc')
            ->join('r.addressedTo', 'ua')
            ->join('r.decisions', 'd')
            ->setFirstResult($firstResult)
            ->setMaxResults($maxResults)
            ->getQuery()
        ;
    }

    public function count()
    {
        return $this->createQueryBuilder('r')
            ->select('count(r.id)')
            ->getQuery()
            ->getSingleScalarResult()
        ;
    }
}
