parameters:

services:
    app.report_manager:
        class: AppBundle\Manager\ReportManager
        arguments: ["@doctrine.orm.entity_manager"]

    app.user_manager:
        class: AppBundle\Manager\UserManager
        arguments: ["@translator", "@request_stack"]
