parameters:

services:
    app.report_manager:
        class: AppBundle\Manager\ReportManager
        arguments: ["@doctrine.orm.entity_manager", "@translator", "@request_stack", "@workflow.report", "@security.token_storage", "@event_dispatcher"]

    app.user_manager:
        class: AppBundle\Manager\UserManager
        arguments: ["@translator", "@request_stack"]
        
    app.report_serializer:
        class: AppBundle\Serializer\ReportNormalizer
        arguments: ["@router", "@app.report_manager", "@app.user_manager", "@templating"]
        tags:
            - { name: serializer.normalizer }

    app.form.type.decision:
        class: AppBundle\Form\DecisionType
        arguments: ["@app.user_manager"]
        tags:
            - { name: form.type }

    app.form.type.report:
        class: AppBundle\Form\ReportType
        arguments: ["@app.user_manager"]
        tags:
            - { name: form.type }

    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }

    app.twig_extension:
        class: AppBundle\Twig\AppExtension
        arguments: ["@app.report_manager", "@app.user_manager"]
        public: false
        tags:
            - { name: twig.extension }

    app.mailer:
        class: AppBundle\Mailer\Mailer
        arguments: ["@mailer", "@templating"]

    app.mailer_listener:
        class: AppBundle\EventListener\MailerListener
        arguments: ['@app.mailer']
        tags:
            - { name: kernel.event_subscriber }
