parameters:

services:
    app.report_manager:
        class: AppBundle\Manager\ReportManager
        arguments: ["@doctrine.orm.entity_manager", "@workflow.report"]

    app.user_manager:
        class: AppBundle\Manager\UserManager
        arguments: ["@translator", "@request_stack"]
        
    app.report_serializer:
        class: AppBundle\Serializer\ReportNormalizer
        arguments: ["@router", "@app.report_manager", "@templating"]
        tags:
            - { name: serializer.normalizer }

    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }

    app.twig_extension:
        class: AppBundle\Twig\AppExtension
        public: false
        tags:
            - { name: twig.extension }